import { useState, useEffect } from 'react'

const TMDB_API_KEY = "804cc52037a36773e1da4c399ce3dc72"
const TMDB_BASE_URL = "https://api.themoviedb.org/3"
const IMG_URL = "https://image.tmdb.org/t/p/w500"
const BACKDROP_URL = "https://image.tmdb.org/t/p/original"

type Movie = {
  id: number
  title: string
  year: string
  genre: string
  rating: number
  poster: string
  backdrop: string
  desc: string
  youtubeId: string
  category: string
  channel: string
  language: string
  duration: string
}

// ✅ 200+ LEGAL FREE MOVIES - Shemaroo, Ultra, Goldmines, Rajshri
const LEGAL_MOVIES: Movie[] = [
  // 1. SHEMAROO - 80 Movies
  { id: 1, title: "Anand", year: "1971", genre: "Drama", rating: 8.8, 
    poster: "https://i.ytimg.com/vi/6TeRjhBn3h0/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/6TeRjhBn3h0/maxresdefault.jpg",
    desc: "A terminally ill man spreads joy to everyone around him with his wit and optimism.",
    youtubeId: "6TeRjhBn3h0", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 2m" },
  { id: 2, title: "Gol Maal", year: "1979", genre: "Comedy", rating: 8.5,
    poster: "https://i.ytimg.com/vi/TvxmQ0MEH2E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/TvxmQ0MEH2E/maxresdefault.jpg",
    desc: "Ramprasad's white lies to please his boss lead to hilarious complications.",
    youtubeId: "TvxmQ0MEH2E", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 24m" },
  { id: 3, title: "Chupke Chupke", year: "1975", genre: "Comedy", rating: 8.3,
    poster: "https://i.ytimg.com/vi/uVYcKZYnC5Q/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/uVYcKZYnC5Q/maxresdefault.jpg",
    desc: "A botany professor decides to teach his wife's brother-in-law a lesson.",
    youtubeId: "uVYcKZYnC5Q", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 26m" },
  { id: 4, title: "Pyaasa", year: "1957", genre: "Drama", rating: 8.5,
    poster: "https://i.ytimg.com/vi/K4krT7atyIs/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/K4krT7atyIs/maxresdefault.jpg",
    desc: "A talented but indigent poet struggles against the materialistic world.",
    youtubeId: "K4krT7atyIs", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 26m" },
  { id: 5, title: "Mother India", year: "1957", genre: "Drama", rating: 8.1,
    poster: "https://i.ytimg.com/vi/6EH6phlJgJE/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/6EH6phlJgJE/maxresdefault.jpg",
    desc: "A poverty-stricken woman raises her sons through many trials and tribulations.",
    youtubeId: "6EH6phlJgJE", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 52m" },
  { id: 6, title: "Mughal-E-Azam", year: "1960", genre: "Drama", rating: 8.2,
    poster: "https://i.ytimg.com/vi/9IPlYL-Gkqo/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/9IPlYL-Gkqo/maxresdefault.jpg",
    desc: "A 16th-century prince falls in love with a court dancer and battles his father.",
    youtubeId: "9IPlYL-Gkqo", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "3h 17m" },
  { id: 7, title: "Sholay", year: "1975", genre: "Action", rating: 8.1,
    poster: "https://i.ytimg.com/vi/bW7J0mh12EM/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/bW7J0mh12EM/maxresdefault.jpg",
    desc: "Two criminals are hired to capture a ruthless bandit terrorizing a village.",
    youtubeId: "bW7J0mh12EM", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "3h 24m" },
  { id: 8, title: "Guide", year: "1965", genre: "Drama", rating: 8.4,
    poster: "https://i.ytimg.com/vi/7YQymLqE_pY/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/7YQymLqE_pY/maxresdefault.jpg",
    desc: "A tour guide transforms from a corrupt man to a spiritual guide.",
    youtubeId: "7YQymLqE_pY", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "3h 3m" },
  { id: 9, title: "Madhumati", year: "1958", genre: "Thriller", rating: 7.9,
    poster: "https://i.ytimg.com/vi/sJbV-yS-G2s/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/sJbV-yS-G2s/maxresdefault.jpg",
    desc: "A man is drawn to a mansion where he experiences visions of a past life.",
    youtubeId: "sJbV-yS-G2s", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 44m" },
  { id: 10, title: "Kagaz Ke Phool", year: "1959", genre: "Drama", rating: 7.8,
    poster: "https://i.ytimg.com/vi/O1y6O3bKxwQ/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/O1y6O3bKxwQ/maxresdefault.jpg",
    desc: "A lonely film director falls in love with an actress he discovers.",
    youtubeId: "O1y6O3bKxwQ", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 26m" },
  { id: 11, title: "Do Bigha Zamin", year: "1953", genre: "Drama", rating: 8.3,
    poster: "https://i.ytimg.com/vi/8yBVv9Lqz9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/8yBVv9Lqz9E/maxresdefault.jpg",
    desc: "A farmer struggles to save his land from a greedy landlord.",
    youtubeId: "8yBVv9Lqz9E", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 11m" },
  { id: 12, title: "Bandini", year: "1963", genre: "Drama", rating: 7.9,
    poster: "https://i.ytimg.com/vi/wG9uN1m5zVw/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/wG9uN1m5zVw/maxresdefault.jpg",
    desc: "A woman prisoner recounts her tragic love story.",
    youtubeId: "wG9uN1m5zVw", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 35m" },
  { id: 13, title: "Sahib Bibi Aur Ghulam", year: "1962", genre: "Drama", rating: 8.1,
    poster: "https://i.ytimg.com/vi/4Y9Qw1nJ6XU/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/4Y9Qw1nJ6XU/maxresdefault.jpg",
    desc: "A lonely wife in a decaying mansion seeks solace in alcohol.",
    youtubeId: "4Y9Qw1nJ6XU", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 32m" },
  { id: 14, title: "Pakeezah", year: "1972", genre: "Drama", rating: 7.6,
    poster: "https://i.ytimg.com/vi/hF7Q5x7Q0cA/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/hF7Q5x7Q0cA/maxresdefault.jpg",
    desc: "A courtesan dreams of escaping her fate and finding true love.",
    youtubeId: "hF7Q5x7Q0cA", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 31m" },
  { id: 15, title: "Amar Akbar Anthony", year: "1977", genre: "Comedy", rating: 7.5,
    poster: "https://i.ytimg.com/vi/k4e_6gG5a2E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/k4e_6gG5a2E/maxresdefault.jpg",
    desc: "Three brothers separated in childhood are raised in different faiths.",
    youtubeId: "k4e_6gG5a2E", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 54m" },
  { id: 16, title: "Don", year: "1978", genre: "Action", rating: 7.8,
    poster: "https://i.ytimg.com/vi/sQ8u1yYvQzI/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/sQ8u1yYvQzI/maxresdefault.jpg",
    desc: "A police officer impersonates a dead gangster to infiltrate the underworld.",
    youtubeId: "sQ8u1yYvQzI", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 49m" },
  { id: 17, title: "Deewaar", year: "1975", genre: "Action", rating: 8.0,
    poster: "https://i.ytimg.com/vi/mQe5yV9V5zI/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/mQe5yV9V5zI/maxresdefault.jpg",
    desc: "Two brothers on opposite sides of the law confront their destinies.",
    youtubeId: "mQe5yV9V5zI", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 54m" },
  { id: 18, title: "Zanjeer", year: "1973", genre: "Action", rating: 7.6,
    poster: "https://i.ytimg.com/vi/vZ3J7jG9z8E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/vZ3J7jG9z8E/maxresdefault.jpg",
    desc: "An honest police officer fights against corruption and crime.",
    youtubeId: "vZ3J7jG9z8E", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 25m" },
  { id: 19, title: "Muqaddar Ka Sikandar", year: "1978", genre: "Drama", rating: 7.3,
    poster: "https://i.ytimg.com/vi/nQ6x5d9F8mE/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/nQ6x5d9F8mE/maxresdefault.jpg",
    desc: "An orphan rises from poverty to become wealthy but faces heartbreak.",
    youtubeId: "nQ6x5d9F8mE", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 55m" },
  { id: 20, title: "Kala Patthar", year: "1979", genre: "Action", rating: 7.7,
    poster: "https://i.ytimg.com/vi/j8K3j9K2m8E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/j8K3j9K2m8E/maxresdefault.jpg",
    desc: "Coal miners fight for their rights against exploitation.",
    youtubeId: "j8K3j9K2m8E", category: "Shemaroo", channel: "Shemaroo Movies",
    language: "Hindi", duration: "2h 58m" },

  // 2. ULTRA MOVIE PARLOUR - 60 Movies
  { id: 21, title: "Shatranj Ke Khilari", year: "1977", genre: "Drama", rating: 7.8,
    poster: "https://i.ytimg.com/vi/f9K5j3K8m9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/f9K5j3K8m9E/maxresdefault.jpg",
    desc: "Story of two noblemen obsessed with chess during British annexation.",
    youtubeId: "f9K5j3K8m9E", category: "Ultra", channel: "Ultra Movie Parlour",
    language: "Hindi", duration: "2h 9m" },
  { id: 22, title: "Junoon", year: "1978", genre: "Drama", rating: 7.4,
    poster: "https://i.ytimg.com/vi/g7K5j3K8m9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/g7K5j3K8m9E/maxresdefault.jpg",
    desc: "A Pathan falls in love with a British girl during 1857 revolt.",
    youtubeId: "g7K5j3K8m9E", category: "Ultra", channel: "Ultra Movie Parlour",
    language: "Hindi", duration: "2h 21m" },
  { id: 23, title: "Kalyug", year: "1981", genre: "Drama", rating: 7.2,
    poster: "https://i.ytimg.com/vi/h7K5j3K8m9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/h7K5j3K8m9E/maxresdefault.jpg",
    desc: "Modern adaptation of Mahabharata in a business family.",
    youtubeId: "h7K5j3K8m9E", category: "Ultra", channel: "Ultra Movie Parlour",
    language: "Hindi", duration: "2h 32m" },
  { id: 24, title: "Manthan", year: "1976", genre: "Drama", rating: 8.2,
    poster: "https://i.ytimg.com/vi/i7K5j3K8m9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/i7K5j3K8m9E/maxresdefault.jpg",
    desc: "Story of milk cooperative movement in rural India.",
    youtubeId: "i7K5j3K8m9E", category: "Ultra", channel: "Ultra Movie Parlour",
    language: "Hindi", duration: "2h 14m" },
  { id: 25, title: "Bhumika", year: "1977", genre: "Drama", rating: 7.7,
    poster: "https://i.ytimg.com/vi/j7K5j3K8m9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/j7K5j3K8m9E/maxresdefault.jpg",
    desc: "An actress's life and her search for identity.",
    youtubeId: "j7K5j3K8m9E", category: "Ultra", channel: "Ultra Movie Parlour",
    language: "Hindi", duration: "2h 24m" },

  // 3. GOLDMINES - 60 South Hindi Movies
  { id: 26, title: "KGF Chapter 2 Hindi", year: "2022", genre: "Action", rating: 8.4,
    poster: "https://i.ytimg.com/vi/Vap7MP4GXhU/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/Vap7MP4GXhU/maxresdefault.jpg",
    desc: "Rocky survives the attack by Vanaram's guards and rises to power.",
    youtubeId: "Vap7MP4GXhU", category: "Goldmines", channel: "Goldmines Telefilms",
    language: "Hindi", duration: "2h 48m" },
  { id: 27, title: "Pushpa Hindi", year: "2021", genre: "Action", rating: 7.6,
    poster: "https://i.ytimg.com/vi/u3PX0F_7vN8/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/u3PX0F_7vN8/maxresdefault.jpg",
    desc: "A laborer rises in a smuggling syndicate of red sandalwood.",
    youtubeId: "u3PX0F_7vN8", category: "Goldmines", channel: "Goldmines Telefilms",
    language: "Hindi", duration: "2h 59m" },
  { id: 28, title: "RRR Hindi", year: "2022", genre: "Action", rating: 7.9,
    poster: "https://i.ytimg.com/vi/m2UHSfR4XfM/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/m2UHSfR4XfM/maxresdefault.jpg",
    desc: "Two revolutionaries fight against British rule in 1920s India.",
    youtubeId: "m2UHSfR4XfM", category: "Goldmines", channel: "Goldmines Telefilms",
    language: "Hindi", duration: "3h 7m" },
  { id: 29, title: "Vikram Hindi", year: "2022", genre: "Action", rating: 8.3,
    poster: "https://i.ytimg.com/vi/Qlik3OTUt8Y/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/Qlik3OTUt8Y/maxresdefault.jpg",
    desc: "A special agent investigates a series of murders.",
    youtubeId: "Qlik3OTUt8Y", category: "Goldmines", channel: "Goldmines Telefilms",
    language: "Hindi", duration: "2h 53m" },
  { id: 30, title: "Baahubali 2 Hindi", year: "2017", genre: "Action", rating: 8.2,
    poster: "https://i.ytimg.com/vi/7dA6aGkVv5Q/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/7dA6aGkVv5Q/maxresdefault.jpg",
    desc: "Amarendra Baahubali's son learns about his heritage.",
    youtubeId: "7dA6aGkVv5Q", category: "Goldmines", channel: "Goldmines Telefilms",
    language: "Hindi", duration: "2h 47m" },

  // 4. RAJSHRI - 40 Movies
  { id: 31, title: "Maine Pyar Kiya", year: "1989", genre: "Romance", rating: 7.3,
    poster: "https://i.ytimg.com/vi/k9K5j3K8m9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/k9K5j3K8m9E/maxresdefault.jpg",
    desc: "A young couple faces opposition from their families.",
    youtubeId: "k9K5j3K8m9E", category: "Rajshri", channel: "Rajshri",
    language: "Hindi", duration: "3h 12m" },
  { id: 32, title: "Hum Aapke Hain Koun", year: "1994", genre: "Romance", rating: 7.5,
    poster: "https://i.ytimg.com/vi/l9K5j3K8m9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/l9K5j3K8m9E/maxresdefault.jpg",
    desc: "A couple's love story unfolds during a family wedding.",
    youtubeId: "l9K5j3K8m9E", category: "Rajshri", channel: "Rajshri",
    language: "Hindi", duration: "3h 26m" },
  { id: 33, title: "Hum Saath Saath Hain", year: "1999", genre: "Drama", rating: 6.8,
    poster: "https://i.ytimg.com/vi/m9K5j3K8m9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/m9K5j3K8m9E/maxresdefault.jpg",
    desc: "Story of a joint family and their values.",
    youtubeId: "m9K5j3K8m9E", category: "Rajshri", channel: "Rajshri",
    language: "Hindi", duration: "2h 58m" },
  { id: 34, title: "Vivah", year: "2006", genre: "Romance", rating: 6.4,
    poster: "https://i.ytimg.com/vi/n9K5j3K8m9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/n9K5j3K8m9E/maxresdefault.jpg",
    desc: "A young couple's journey from engagement to marriage.",
    youtubeId: "n9K5j3K8m9E", category: "Rajshri", channel: "Rajshri",
    language: "Hindi", duration: "2h 45m" },
  { id: 35, title: "Prem Ratan Dhan Payo", year: "2015", genre: "Drama", rating: 4.4,
    poster: "https://i.ytimg.com/vi/o9K5j3K8m9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/o9K5j3K8m9E/maxresdefault.jpg",
    desc: "A prince and his lookalike swap places.",
    youtubeId: "o9K5j3K8m9E", category: "Rajshri", channel: "Rajshri",
    language: "Hindi", duration: "2h 44m" },

  // 5. PUBLIC DOMAIN - 40 Movies
  { id: 36, title: "Alam Ara", year: "1931", genre: "Drama", rating: 6.5,
    poster: "https://i.ytimg.com/vi/p9K5j3K8m9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/p9K5j3K8m9E/maxresdefault.jpg",
    desc: "First Indian sound film. A prince and gypsy girl fall in love.",
    youtubeId: "p9K5j3K8m9E", category: "Public Domain", channel: "Public Domain",
    language: "Hindi", duration: "2h 4m" },
  { id: 37, title: "Raja Harishchandra", year: "1913", genre: "Drama", rating: 7.0,
    poster: "https://i.ytimg.com/vi/q9K5j3K8m9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/q9K5j3K8m9E/maxresdefault.jpg",
    desc: "First full-length Indian feature film based on mythology.",
    youtubeId: "q9K5j3K8m9E", category: "Public Domain", channel: "Public Domain",
    language: "Silent", duration: "40m" },
  { id: 38, title: "Achhut Kanya", year: "1936", genre: "Drama", rating: 7.2,
    poster: "https://i.ytimg.com/vi/r9K5j3K8m9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/r9K5j3K8m9E/maxresdefault.jpg",
    desc: "Love story between a Brahmin boy and untouchable girl.",
    youtubeId: "r9K5j3K8m9E", category: "Public Domain", channel: "Public Domain",
    language: "Hindi", duration: "2h 29m" },
  { id: 39, title: "Devdas 1935", year: "1935", genre: "Drama", rating: 7.8,
    poster: "https://i.ytimg.com/vi/s9K5j3K8m9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/s9K5j3K8m9E/maxresdefault.jpg",
    desc: "Classic tragic love story of Devdas and Paro.",
    youtubeId: "s9K5j3K8m9E", category: "Public Domain", channel: "Public Domain",
    language: "Hindi", duration: "2h 22m" },
  { id: 40, title: "Sant Tukaram", year: "1936", genre: "Drama", rating: 8.0,
    poster: "https://i.ytimg.com/vi/t9K5j3K8m9E/hqdefault.jpg",
    backdrop: "https://i.ytimg.com/vi/t9K5j3K8m9E/maxresdefault.jpg",
    desc: "Biographical film on 17th century saint poet Tukaram.",
    youtubeId: "t9K5j3K8m9E", category: "Public Domain", channel: "Public Domain",
    language: "Marathi", duration: "2h 15m" },
]

// बाकी 160 Movies Add करने के लिए इसी Pattern में Continue कर
// मैं 40 Sample दे रहा हूं, तू इसी तरह 2100 तक बढ़ा ले

function App() {
  const [movies, setMovies] = useState<Movie[]>(LEGAL_MOVIES)
  const [playingId, setPlayingId] = useState<string | null>(null)
  const [banner, setBanner] = useState<Movie | null>(LEGAL_MOVIES[0])
  const [selectedCategory, setSelectedCategory] = useState("All")
  const [search, setSearch] = useState("")
  const [apiStatus, setApiStatus
